version: '3'

services:
  phoenix:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - app:/app
    command:
      - ./run.sh
  redis:
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/"
  redis:
